version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build-docker:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - run: echo "docker executor"
  build-linux:
    machine:
      image: ubuntu-2204:current
    steps:
      - run: echo "linux executor"
  build-macos:
    macos:
      xcode: 14.2.0
    steps:
      - run: echo "macos executor"
  build-windows:
    executor: win/server-2022
    steps:
      - run: echo "windows executor"


workflows:
  build-docker-workflow:
    jobs:
      - build-docker
  build-linux-workflow:
    jobs:
      - build-linux
  build-macos-workflow:
    jobs:
      - build-macos
  build-windows-workflow:
    jobs:
      - build-windows