version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "Building complete"
  test-node:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - run: echo "Testing complete"
  test-node-16:
    docker:
      - image: cimg/node:16.18.0
    steps:
      - run: echo "Testing complete"
  test-node-14:
    docker:
      - image: cimg/node:14.20.1
    steps:
      - run: echo "Testing complete"
  deploy:
      docker:
        - image: cimg/base:2022.10
      steps:
        - run: echo "DEPLOYING" # Make sure all tests pass first!

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test-node:
          requires:
            - build
      - test-node-16:
          requires:
            - build
      - test-node-14:
          requires:
            - build
      - deploy:
          requires:
            - test-node
            - test-node-16
            - test-node-14