version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Json Cache
          keys: cache1
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Json Cache
          key: cache1
          paths:
            - ~/.cache/yarn

workflows:
  cache-save-and-restore:
    jobs:
      - build