version: 2.1

parameters:
  condition-workflow:
    type: boolean
    default: false

jobs:
  my-job:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - when:
          condition:
            # Add condition to execute this step when the github branch is equal to 'main'
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run: echo "I am on main"

  conditional-job:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run: echo "This ran on a pipeline parameter"

workflows:
  my-workflow:
    jobs:
      - my-job

  conditional-workflow:
    when:
      equal: [true, << pipeline.parameters.condition-workflow >> ]
        # Add condition to execute this workflow when condition-workflow is equal to true
    jobs:
      - conditional-job